"""exams_attended

Revision ID: 0fde9ebaccf8
Revises: 272a939386c9
Create Date: 2024-03-21 19:01:08.005773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fde9ebaccf8'
down_revision: Union[str, None] = '272a939386c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('exams_attended', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'exams_attended')
    # ### end Alembic commands ###
