"""exams

Revision ID: 272a939386c9
Revises: 62bc1167b4d2
Create Date: 2024-03-11 21:13:33.830225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272a939386c9'
down_revision: Union[str, None] = '62bc1167b4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('qstn_count', sa.Integer(), nullable=False),
    sa.Column('mark_each', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('answer_key', sa.Text(), nullable=True),
    sa.Column('answers', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('contestants', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution'], ['institutions.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exams')
    # ### end Alembic commands ###
